"""Task C4: consolidate the download surfaces into Exports.

The Exports tab (`data-kind="data"`) already aggregates per-run raw-emitter
downloads (`_loadRawData` / `#raw-data-list`, Fable §4.8) AND analysis result
files (`#data-files` / `#data-download-all`) — it is the single "get the
data" tab. The Readouts tab used to render a SECOND, full raw-download
widget (`#readouts-download`, populated by `_loadReadoutsDownload()` /
`_downloadAllRawData()`), duplicating the same per-run links Exports already
shows. C4 removes that duplicate widget and replaces it with a single
pointer that jumps to Exports via C1's `_gotoStudyTab('data', <anchor>)`.

See .superpowers/sdd/fable-increment-a/task-C4-brief.md.
"""
from __future__ import annotations

import pathlib
import tempfile
from pathlib import Path

from vivarium_workbench.lib.study_page import render_study_detail_html

_PKG = Path(__file__).parent.parent / "vivarium_workbench"


def _render(spec_extra=None):
    spec = {"name": "s1"}
    if spec_extra:
        spec.update(spec_extra)
    with tempfile.TemporaryDirectory() as d:
        return render_study_detail_html(pathlib.Path(d), "s1", spec)


# ---------------------------------------------------------------------------
# Template
# ---------------------------------------------------------------------------

def test_readouts_panel_no_longer_inlines_full_widget_markup():
    html = _render()
    # The mount point stays (JS decides pointer-vs-nothing at runtime) ...
    assert 'id="readouts-download"' in html
    # ... but the old widget's own markup (only ever JS-injected) must not be
    # statically present, and none of its literal strings leak into the
    # template either.
    assert "Download raw data</strong>" not in html


def test_exports_panel_unchanged_download_surfaces_present():
    """Exports must remain a superset: both download surfaces it already had
    (per-run raw data + analysis files) are still there, plus a new anchor
    id for the Readouts pointer to jump to."""
    html = _render()
    assert 'id="raw-data-list"' in html
    assert 'id="data-files"' in html
    assert 'id="data-download-all"' in html
    assert 'id="exports-downloads"' in html


def test_exports_bulk_download_button_present_hidden_by_default():
    """Review round 1 fix: the old Readouts widget's bulk "download all raw
    runs" convenience is a genuine capability, not just a set of per-run
    links — restore it AT the Exports raw-download group (not the unrelated
    analysis-file zip button). Static markup starts hidden; JS reveals it
    with a run count once /api/simulations resolves."""
    html = _render()
    assert 'id="raw-data-download-all"' in html
    assert 'onclick="_downloadAllRawExports()"' in html
    # Starts hidden — _loadRawData only reveals it once there's ≥1 run with
    # raw data (never shown for a study with zero downloadable runs).
    i = html.index('id="raw-data-download-all"')
    tag = html[max(0, i - 80):i + 120]
    assert "display:none" in tag
    # Scoped to the raw-run group, distinct from the analysis-file zip.
    assert 'id="data-download-all"' in html


# ---------------------------------------------------------------------------
# JS: old full-widget functions removed; replaced by a lightweight pointer.
#
# Grepped the whole repo (static/, templates/, tests/) for other callers of
# _loadReadoutsDownload / _downloadAllRawData before writing this: the only
# hits outside vivarium_workbench/static/study-detail.js are pre-generated,
# published read-only-dashboard bundle copies under
# tests/_fixtures/*/reports/assets/study-detail.js (regenerated by
# vivarium-workbench-publish, not hand-authored, not imported by any test) —
# so it's safe to delete both functions outright.
# ---------------------------------------------------------------------------

def test_old_full_download_widget_functions_removed():
    js = (_PKG / "static" / "study-detail.js").read_text(encoding="utf-8")
    assert "function _loadReadoutsDownload(" not in js
    assert "function _downloadAllRawData(" not in js
    assert "window._loadReadoutsDownload " not in js
    assert "window._loadReadoutsDownload=" not in js
    assert "window._downloadAllRawData" not in js


def test_readouts_tab_activation_calls_pointer_not_old_widget():
    js = (_PKG / "static" / "study-detail.js").read_text(encoding="utf-8")
    i = js.index("function _setStudyTab(")
    j = js.index("window._setStudyTab", i)
    body = js[i:j]
    assert "_loadReadoutsDownload()" not in body
    assert "_loadReadoutsDownloadPointer(" in body


def test_pointer_function_jumps_to_exports_via_gotostudytab():
    js = (_PKG / "static" / "study-detail.js").read_text(encoding="utf-8")
    assert "function _loadReadoutsDownloadPointer(" in js
    assert "window._loadReadoutsDownloadPointer = _loadReadoutsDownloadPointer;" in js
    i = js.index("function _loadReadoutsDownloadPointer(")
    j = js.index("window._loadReadoutsDownloadPointer", i)
    body = js[i:j]
    # Reuses C1's cross-tab helper — no bespoke tab-switch logic. (The call
    # is embedded in an onclick="..." HTML-attribute string, so its quotes
    # are backslash-escaped in the JS source: _gotoStudyTab(\'results\',...).)
    # Task E2 moved the raw-data-downloads group off Exports ('data') onto
    # Simulations ('simulate'); the study-spine reorg (spec §3.3) moved it
    # again, onto its own Results panel ('results'), and repointed this
    # pointer to match.
    assert "_gotoStudyTab(" in body
    assert "gotoStudyTab(\\'results\\'" in body
    # Lands on the anchor the Results template now carries.
    assert "exports-downloads" in body
    # Same data source + filter predicate _loadResults (Results) uses, so the
    # pointer only appears when Results actually has something to show —
    # never pointing at an empty tab (brief: "prefer omitting the pointer
    # when there are no runs with data").
    assert "/api/simulations" in body
    assert "store_path" in body and "db_path" in body


def test_pointer_omits_itself_when_no_downloadable_data():
    js = (_PKG / "static" / "study-detail.js").read_text(encoding="utf-8")
    i = js.index("function _loadReadoutsDownloadPointer(")
    j = js.index("window._loadReadoutsDownloadPointer", i)
    body = js[i:j]
    # withData.length gates whether anything renders at all (not just an
    # empty-state message) — the omit-when-empty behavior the brief prefers.
    assert "withData.length" in body


def test_exports_raw_data_loader_unchanged_still_present():
    """Regression guard: Results' own per-run download loader (_loadResults,
    renamed from _loadRawData by the study-spine reorg, spec §3.3) — the
    thing that makes Results a superset of the old Readouts widget — must
    still exist, still mount #raw-data-list, and still build real
    /api/simulation-run-download links."""
    js = (_PKG / "static" / "study-detail.js").read_text(encoding="utf-8")
    assert "function _loadResults(" in js
    assert "window._loadResults = _loadResults;" in js
    assert "getElementById('raw-data-list')" in js
    assert "/api/simulation-run-download?run_id=" in js


def test_loadrawdata_reveals_and_labels_the_bulk_button():
    """_loadResults is what knows N (runs with store_path/db_path) — it must
    reveal #raw-data-download-all with that count when N > 0, and keep it
    hidden for a study with zero downloadable runs (no bulk button pointing
    at nothing)."""
    js = (_PKG / "static" / "study-detail.js").read_text(encoding="utf-8")
    i = js.index("function _loadResults(")
    j = js.index("window._loadResults = _loadResults;", i)
    body = js[i:j]
    assert "getElementById('raw-data-download-all')" in body
    assert "withDataCount" in body
    assert "bulkBtn.style.display = withDataCount ? '' : 'none'" in body


def test_downloadallrawexports_defined_and_scoped_to_raw_data_list():
    """Review round 1 fix: restores the old _downloadAllRawData's sequential-
    download technique (iterate a[download] links, trigger each via a
    synthetic <a>+click with a stagger), scoped to #raw-data-list — NOT the
    old #readouts-download host, and NOT the analysis-file zip button."""
    js = (_PKG / "static" / "study-detail.js").read_text(encoding="utf-8")
    assert "function _downloadAllRawExports(" in js
    assert "window._downloadAllRawExports = _downloadAllRawExports;" in js
    i = js.index("function _downloadAllRawExports(")
    j = js.index("window._downloadAllRawExports", i)
    body = js[i:j]
    assert "getElementById('raw-data-list')" in body
    assert "querySelectorAll('a[download]')" in body
    assert "setTimeout(" in body
    assert "readouts-download" not in body


def test_simulations_per_row_data_links_left_alone():
    """Out of scope: the Simulations tab's contextual per-row Data links
    (sim-table.js) are untouched by this task."""
    js = (_PKG / "static" / "sim-table.js").read_text(encoding="utf-8")
    assert "/api/simulation-run-download?run_id=" in js


def test_js_syntax_valid():
    import subprocess
    r = subprocess.run(
        ["node", "--check", str(_PKG / "static" / "study-detail.js")],
        capture_output=True, text=True,
    )
    assert r.returncode == 0, r.stderr
