"""Guard: no git-tracked symlinks, and no tracked build artifacts.

Regression for #582. A local dev symlink `vivarium_workbench/loom/_dist ->
/Users/<author>/.../loom/_dist` was accidentally committed (the .gitignore
pattern `loom/_dist/` had a trailing slash, so it only matched a directory and
let the symlink through). On every machine but the author's that symlink is
DANGLING, so:

  * `vite build` fails with `ENOENT: mkdir _dist` while building the loom bundle,
  * hatchling's wheel packaging then hard-fails `os.stat`-ing the dangling link,

which broke `uv pip install "vivarium-workbench @ git+...@main"` — and therefore
the read-only-dashboard publish CI — in EVERY downstream workspace (v2ecoli,
sms-ecoli, and the pbg-* demos).

The failure surfaced far downstream and was expensive to trace. This guard makes
the whole class impossible to reintroduce: a tracked symlink (mode 120000) fails
here, at PR time, in this repo — not in a consumer's publish job days later.
"""
from __future__ import annotations

import subprocess
from pathlib import Path


def _repo_root() -> Path:
    out = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        cwd=Path(__file__).resolve().parent,
        capture_output=True, text=True, check=True,
    ).stdout.strip()
    return Path(out)


def _tracked_entries(root: Path) -> list[tuple[str, str]]:
    """(mode, path) for every git-tracked file. Mode 120000 == symlink."""
    out = subprocess.run(
        ["git", "ls-files", "-s"],
        cwd=root, capture_output=True, text=True, check=True,
    ).stdout
    entries: list[tuple[str, str]] = []
    for line in out.splitlines():
        if not line:
            continue
        meta, _, path = line.partition("\t")
        mode = meta.split(" ", 1)[0]
        entries.append((mode, path))
    return entries


def test_no_tracked_symlinks():
    """No file is committed as a symlink (mode 120000).

    Tracked symlinks dangle in fresh checkouts and break downstream builds; a
    generated bundle or a machine-local path must never be committed as a link.
    """
    root = _repo_root()
    symlinks = [path for mode, path in _tracked_entries(root) if mode == "120000"]
    assert not symlinks, (
        "git-tracked symlinks are banned — they dangle in every fresh checkout "
        "and break the wheel/loom build for all downstream publishers (see #582). "
        f"Remove and gitignore these: {symlinks}"
    )


def test_generated_loom_artifacts_are_not_tracked():
    """The vendored-loom build outputs must stay gitignored, never committed.

    `_dist` (the Vite bundle) and `node_modules` are generated by
    scripts/build_loom.sh; committing either (as a dir OR a symlink) is what #582
    fixed. Assert they carry no tracked entries so the fix can't silently regress.
    """
    root = _repo_root()
    tracked = {path for _, path in _tracked_entries(root)}
    offenders = sorted(
        p for p in tracked
        if p.startswith("vivarium_workbench/loom/_dist")
        or p.startswith("vivarium_workbench/loom/node_modules")
    )
    assert not offenders, (
        "vendored-loom build artifacts must stay gitignored (generated by "
        f"scripts/build_loom.sh), but these are tracked: {offenders}"
    )
